"""Translate the Mermaid diagram sources to Spanish (figNN.mmd -> figNN_es.mmd)."""
import glob, os

# Replacements applied longest-key-first so phrases win over words.
R = {
    "4 labels: background /<br/>medulla / pons / mesencephalon": "4 clases: fondo /<br/>bulbo / protuberancia / mesencéfalo",
    "Axial slices 80 x 80<br/>(train: keep slices with<br/>&ge;20 fg voxels)": "Cortes axiales 80 x 80<br/>(entren.: cortes con<br/>&ge;20 vóxeles fg)",
    "N4 bias-field<br/>correction": "Corrección de<br/>campo de sesgo N4",
    "Affine registration<br/>to MNI space": "Registro afín<br/>al espacio MNI",
    "Crop to brainstem FOV<br/>80 x 80 x 96": "Recorte a FOV tronco<br/>80 x 80 x 96",
    "Per-volume<br/>z-score normalisation": "Normalización z<br/>por volumen",
    "Full volumes<br/>80 x 80 x 96": "Volúmenes completos<br/>80 x 80 x 96",
    "Geometric + intensity<br/>augmentation": "Aumentación geométrica<br/>+ de intensidad",
    "Model training": "Entrenamiento del modelo",
    "No augmentation": "Sin aumentación",
    "Encoder: DoubleConv stages": "Codif.: etapas DoubleConv",
    "Encoder: CompetitiveDense blocks": "Codif.: bloques CompetitiveDense",
    "Encoder: 5 levels of<br/>Inception blocks (InstanceNorm)": "Codif.: 5 niveles de<br/>bloques Inception (InstanceNorm)",
    "Encoder: PreAct-Res stages": "Codif.: etapas PreAct-Res",
    "Encoder: MultiScale PreAct blocks": "Codif.: bloques MultiScale PreAct",
    "Decoder: ConvTranspose +": "Decod.: ConvTranspose +",
    "Decoder: MaxUnpool (indices) +": "Decod.: MaxUnpool (índices) +",
    "Decoder: PreAct-Res, concat skips": "Decod.: PreAct-Res, saltos concat",
    "CNN decoder<br/>(ConvTranspose), concat skips": "Decod. CNN<br/>(ConvTranspose), saltos concat",
    "attention-refined skips": "saltos refinados por atención",
    "CBAM-gated skips": "saltos con compuerta CBAM",
    "concat skips": "saltos concat",
    "uniform 160 ch + MaxPool (indices)": "160 can. uniforme + MaxPool (índices)",
    "competitive maxout + MultiScale": "maxout competitivo + MultiScale",
    "Bottleneck features x": "Cuello de botella x",
    "Bottleneck": "Cuello de botella",
    "Global avg pool -> C-vector": "Prom. global -> vector C",
    "Global avg pool": "Promediado global",
    "Linear -> n_qubits, tanh*pi": "Lineal -> n_qubits, tanh*pi",
    "Variational quantum circuit": "Circuito cuántico variacional",
    "Angle embedding<br/>R_y(x_i) on each qubit": "Codif. de ángulos<br/>R_y(x_i) por qubit",
    "Entangling layers": "Capas de entrelazamiento",
    "Readout:<br/>&lang;Z_i&rang; expectation per qubit": "Lectura:<br/>valor esp. &lang;Z_i&rang; por qubit",
    "channel vector<br/>(B, n_q)": "vector de canales<br/>(B, n_q)",
    "output vector<br/>(B, n_q)": "vector de salida<br/>(B, n_q)",
    "Input -> patch partition": "Entrada -> partición en parches",
    "Input -> stem conv": "Entrada -> conv inicial",
    "Input 1x80x80": "Entrada 1x80x80",
    "Trained model + 6 test subjects": "Modelo entrenado + 6 sujetos de prueba",
    "Foreground-only 2D<br/>(slices with >=20 fg voxels)": "Solo primer plano 2D<br/>(cortes con >=20 vóxeles fg)",
    "Full-volume 2D<br/>(all 96 slices)": "Volumen completo 2D<br/>(los 96 cortes)",
    "3D volumetric<br/>(whole volume)": "3D volumétrico<br/>(volumen completo)",
    "micro-Dice + per-subject Dice": "micro-Dice + Dice por sujeto",
    "per-subject Dice (honest)": "Dice por sujeto (honesto)",
    "per-subject Dice": "Dice por sujeto",
    "Friedman + paired Wilcoxon<br/>+ bootstrap CIs + Cohen's d": "Friedman + Wilcoxon pareado<br/>+ IC bootstrap + d de Cohen",
    "9 architectures x 2 dims<br/>= 18 configurations": "9 arquitecturas x 2 dim<br/>= 18 configuraciones",
    "Train to ~17M params<br/>up to 400 ep, early stop": "Entrenar a ~17M par.<br/>hasta 400 ep, parada temprana",
    "Evaluate on 6 test subjects": "Evaluar en 6 sujetos de prueba",
    "2D quantum native ~6.1M<br/>(NOT param-matched)": "2D cuántico nativo ~6.1M<br/>(NO equiparado)",
    "Param-matched 2D rerun<br/>quantum 4-stage = 16.9M": "Reejecución 2D equiparada<br/>cuántico 4 etapas = 16.9M",
    "Foreground-only Dice": "Dice solo primer plano",
    "Honest full-volume 2D re-eval": "Reeval. honesta vol. completo 2D",
    "Aggregate + statistics": "Agregación + estadística",
    "Methods audit + corrections": "Auditoría de métodos + correcciones",
    "Per-subject<br/>segmentations": "Segmentaciones<br/>por sujeto",
    "Register to common<br/>MNI template": "Registrar a plantilla<br/>MNI común",
    "Voxel-wise statistics<br/>(z-score / Jacobian)": "Estadística por vóxel<br/>(z-score / Jacobiano)",
    "Population atrophy map<br/>+ probabilistic atlas": "Mapa de atrofia poblacional<br/>+ atlas probabilístico",
    "Correlate with SARA score<br/>and CAG repeat length": "Correlacionar con SARA<br/>y longitud de repetición CAG",
    "Imaging biomarker": "Biomarcador de imagen",
    "Inception block": "Bloque Inception",
    "Inception, attention-refined skips": "Inception, saltos refinados por atención",
    "Skip refinement": "Refinamiento de saltos",
    "CBAM: channel + spatial attention": "CBAM: atención de canal + espacial",
    "PreAct-Res block": "Bloque PreAct-Res",
    "MultiScale PreAct block": "Bloque MultiScale PreAct",
    "DoubleConv block": "Bloque DoubleConv",
    "CompetitiveDense unit (x3)": "Unidad CompetitiveDense (x3)",
    "CompetitiveDense": "CompetitiveDense",
    "integrate Conv 3x3": "Conv de integración 3x3",
    "Enc stage": "Etapa codif.",
    "Dec stage": "Etapa decod.",
    "Enc 1": "Codif. 1", "Enc 2": "Codif. 2", "Enc 3": "Codif. 3",
    "Dec 1": "Decod. 1", "Dec 2": "Decod. 2", "Dec 3": "Decod. 3",
    "Swin stage": "Etapa Swin",
    "Input": "Entrada",
    "Train: 27": "Entren.: 27",
    "Validation: 6": "Validación: 6",
    "Test: 6": "Prueba: 6",
    "subjects": "sujetos",
    "except a37": "excepto a37",
    "skip": "salto",
    "pool": "pool",
    "up": "subir",
    "1x1 conv -> 4 classes": "conv 1x1 -> 4 clases",
}

keys = sorted(R, key=len, reverse=True)
for f in glob.glob("paper/figures/fig[0-9][0-9].mmd"):
    s = open(f).read()
    for k in keys:
        s = s.replace(k, R[k])
    out = f.replace(".mmd", "_es.mmd")
    open(out, "w").write(s)
print("translated", len(glob.glob("paper/figures/fig[0-9][0-9].mmd")), "diagrams")
