flowchart LR
  I["Entrada -> conv inicial"] --> E["Codif.: etapas PreAct-Res<br/>[44,88,176,240], 2 blocks/stage"]
  E --> B["Cuello de botella<br/>2x PreAct-Res"]
  B --> D["Decod.: ConvTranspose +<br/>PreAct-Res, saltos concat"]
  D --> H["conv 1x1 -> 4 clases"]
  subgraph block["Bloque PreAct-Res"]
    direction LR
    n1["InstanceNorm"] --> r1["ReLU"] --> c1["Conv"] --> add(("+"))
    in["x"] --> add
  end
